version: "3.8"

services:
  notification_api:
    image: notification_crud
    container_name: notification_api_application
    ports:
      - "5001:5001"
      # - "5002:5002"
    depends_on:
      - message-broker
    environment:
      - "RabbitMqSettingRelease__Password=goblinusik111"
      - "RabbitMqSettingRelease__Login=faith"
      - "RabbitMqSettingRelease__Host=rabbitmq:5672"
    networks:
      - rabbitmq_network

  authorize_api:
    image: authorize_crud
    container_name: authorize_api_application
    ports:
      - "5101:5101"
      - "5102:5102"
    environment:
      - "RabbitMqSetting__Password=goblinusik111"
      - "RabbitMqSetting__Login=faith"
      - "RabbitMqSetting__Host=rabbitmq:5672"
      - "ConnectionStrings__RedisConnection=redis-db:6379"
      - "ConnectionStrings__SQLServerConnection=Server=auth-database, 1433;Database=StoreAuthentication;User Id=sa;Password=goblinusik111W;MultipleActiveResultSets=true;TrustServerCertificate=True;"
      - "APIList__ProductAPI=https://product_api:5202/api"
      - "ApiList__Frontend=https://main_proxy_api:5402"
      - ASPNETCORE_URLS=https://+:5102;http://+:5101
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\zelen\.aspnet\https:/https:ro
    networks:
      - rabbitmq_network
    depends_on:
      - message-broker
      - auth-database
      - redis-db

  product_api:
    image: product_crud
    container_name: product_api_application
    ports:
      - "5201:5201"
      - "5202:5202"
    environment:
      - "MassTransitSetting__Password=goblinusik111"
      - "MassTransitSetting__Login=faith"
      - "MassTransitSetting__Host=rabbitmq:5672"
      - "ConnectionStrings__SQLServerConnection=Server=auth-database, 1433;Database=CRUDProducts;User Id=sa;Password=goblinusik111W;MultipleActiveResultSets=true;TrustServerCertificate=True;"
      - "ConnectionStrings__RedisConnection=redis-db:6379"
      - "BlobStorage__Port=10000"
      - "BlobStorage__Key=ZGV2c3RvcmVhY2NvdW50Mw=="
      - "BlobStorage__AccountName=faith725"
      - "BlobStorage__BaseUrl=http://azurite"
      - "APIList__AuthorizeAPI=https://authorize_api:5102/api"
      - "APIList__Frontend=https://main_proxy_api:5402"
      - "APIList__PromethesAPI=http://prometheus:9090"
      - ASPNETCORE_URLS=https://+:5202;http://+:5201
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\zelen\.aspnet\https:/https:ro
    networks:
      - rabbitmq_network
    depends_on:
      - message-broker
      - auth-database
      - azurite
      - prometheus

  message_api:
    image: message_crud
    container_name: message_api_aplication
    ports:
      - 5301:5301
      - 5302:5302
    environment:
      - "ApiList__ProductApi=https://product_api:5202/api"
      - "ApiList__Frontend=https://main_proxy_api:5402"
      - "ConnectionStrings__RedisConnection=redis-db:6379"
      - ASPNETCORE_URLS=https://+:5302;http://+:5301
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\zelen\.aspnet\https:/https:ro
    networks:
      - rabbitmq_network
    depends_on:
      - redis-db
  
  main_proxy_api:
    image: proxy_crud
    container_name: reverse_proxy_application
    ports:
      - "5401:5401"
      - "5402:5402"
    environment:
      - "ApiList__FrontendHttp=http://localhost:8080"
      - "ApiList__FrontendHttps=https://localhost:8081"
      - ASPNETCORE_URLS=https://+:5402;http://+:5401
      - ASPNETCORE_Kestrel__Certificates__Default__Password=goblinusik111
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - C:\Users\zelen\.aspnet\https:/https:ro
    networks:
      - rabbitmq_network
    depends_on:
      - message_api
      - authorize_api
      - product_api

  frontend:
    image: frontend_crud
    container_name: frondend_application
    environment:
      - DEFAULT_CONF=C:\VSProjects\CourceCRUD\frontend\CRUD\nginx.conf
      - SERVER_CONF=C:\VSProjects\CourceCRUD\frontend\CRUD\default.conf
    ports:
      - "8081:5173"
      - "8080:80"
    networks:
      - rabbitmq_network
    depends_on:
      - main_proxy_api

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: files-storages
    volumes:
      - ./.containers/blob_storage/data:/data
    ports:
      - '10000:10000'
    environment:
      - AZURITE_ACCOUNTS=faith725:ZGV2c3RvcmVhY2NvdW50Mw==
    networks:
      - rabbitmq_network

  message-broker:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=faith
      - RABBITMQ_DEFAULT_PASS=goblinusik111
    networks:
      - rabbitmq_network

  auth-database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ms_sql_database
    ports:
      - "1333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=goblinusik111W
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - rabbitmq_network

  redis-db:
    image: redis/redis-stack:latest
    container_name: redis-db
    ports:
      - "6379:6379"
    networks:
      - rabbitmq_network
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus-telemetry
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - rabbitmq_network
    
volumes:
  sqlvolume:
    driver: local

networks:
  app_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge