scrape_configs:
  - job_name: "product-web"
    scrape_interval: 15s
    scrape_timeout: 10s
    # metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["product_api:5202"]

    tls_config:
      insecure_skip_verify: true

